Add imports
This is gonna get worse before it gets better, isnt it.

root@c7d36ed66969:~/editor# stack build
Warning (added by new or init): Specified resolver could not satisfy all
dependencies. Some external packages have been added as dependencies.
You can suppress this message by removing it from stack.yaml

No packages found in snapshot which provide a "happy" executable, which
is a build-tool dependency of "haskell-src-exts"
Missing build-tools may be caused by dependencies of the build-tool
being overridden by extra-deps.
This should be fixed soon - see this issue
https://github.com/commercialhaskell/stack/issues/595

editor-0.1.0.0: build
Preprocessing library editor-0.1.0.0...
[5 of 5] Compiling Modes            ( src/Modes.hs,
.stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Modes.o )

/root/editor/src/Modes.hs:71:11: error:
Couldn't match type Void
with State (Root (Module SrcSpanInfo))
Expected type: m (State (Root (Module SrcSpanInfo)))
Actual type: EitherT
(State
(BuildsOn (Root (Module SrcSpanInfo) ==> C_Module SrcSpanInfo)))
m3
Void
In the expression: runEditorMode $ set zipper z' s
In a case alternative: Just z' -> runEditorMode $ set zipper z' s
In the second argument of (<$>), namely
case descendPrism _Module' $ view zipper s of {
Nothing
-> do { liftIO $ print "wrong kind of module";
return s }
Just z' -> runEditorMode $ set zipper z' s }

/root/editor/src/Modes.hs:81:5: error:
Couldn't match type Void
with State (z ==> C_Module SrcSpanInfo)
Expected type: m (Either
(State (BuildsOn (z ==> C_Module SrcSpanInfo)))
(State (z ==> C_Module SrcSpanInfo)))
Actual type: m (Either (State z) Void)
In the expression:
Right
<$> runEditorMode (over zipper (descendLens (_Wrapped . _5)) s)
In an equation for handleKeyEvent:
handleKeyEvent (KChar 'd', []) s
= Right
<$> runEditorMode (over zipper (descendLens (_Wrapped . _5)) s)
In the instance declaration for
EditorMode (z ==> C_Module SrcSpanInfo)
Relevant bindings include
s :: State (z ==> C_Module SrcSpanInfo)
(bound at src/Modes.hs:80:34)
handleKeyEvent :: (Key, [Modifier])
-> State (z ==> C_Module SrcSpanInfo)
-> m (Either
(State (BuildsOn (z ==> C_Module SrcSpanInfo)))
(State (z ==> C_Module SrcSpanInfo)))
(bound at src/Modes.hs:79:3)

/root/editor/src/Modes.hs:97:11: error:
Couldn't match type Void
with State (z ==> [Decl SrcSpanInfo])
Expected type: m (State (z ==> [Decl SrcSpanInfo]))
Actual type: EitherT
(State
(BuildsOn ((z ==> [Decl SrcSpanInfo]) =*=> Decl SrcSpanInfo)))
m1
Void
In the expression: runEditorMode $ set zipper z' s
In a case alternative: Just z' -> runEditorMode $ set zipper z' s
In the second argument of (<$>), namely
case descendList $ view zipper s of {
Nothing
-> do { liftIO $ print "can't descend into empty list";
return s }
Just z' -> runEditorMode $ set zipper z' s }
Relevant bindings include
z' :: (z ==> [Decl SrcSpanInfo]) =*=> Decl SrcSpanInfo
(bound at src/Modes.hs:96:14)
s :: State (z ==> [Decl SrcSpanInfo]) (bound at src/Modes.hs:90:34)
handleKeyEvent :: (Key, [Modifier])
-> State (z ==> [Decl SrcSpanInfo])
-> m (Either
(State (BuildsOn (z ==> [Decl SrcSpanInfo])))
(State (z ==> [Decl SrcSpanInfo])))
(bound at src/Modes.hs:89:3)

/root/editor/src/Modes.hs:149:3: error:
Could not deduce (Monoid (State (BuildsOn z)))
arising from a use of nextKeyEvent
from the context: (MMonad z m, EditorMode z)
bound by the type signature for:
handleNextKeyEvent :: (MMonad z m, EditorMode z) =>
StateT (State z) (EitherT (State (BuildsOn z)) m) ()
at src/Modes.hs:147:1-104
In the first argument of (>>=), namely nextKeyEvent
In the expression: nextKeyEvent >>= juggle handleKeyEvent
In an equation for handleNextKeyEvent:
handleNextKeyEvent = nextKeyEvent >>= juggle handleKeyEvent

/root/editor/src/Modes.hs:155:13: error:
Data constructor not in scope:
StateT :: (s -> m ((), s)) -> StateT s m ()
Perhaps you meant State (line 35)
Perhaps you want to add StateT to the import list
in the import of Control.Monad.State (src/Modes.hs:20:1-80).

/root/editor/src/Modes.hs:158:17: error:
Variable not in scope:
evalStateT :: t0 -> State z -> EitherT (State (BuildsOn z)) m Void
Perhaps you meant execStateT (imported from Control.Monad.State)
Perhaps you want to add evalStateT to the import list
in the import of Control.Monad.State (src/Modes.hs:20:1-80).

/root/editor/src/Modes.hs:158:30: error:
Variable not in scope:
forever
:: StateT (State z0) (EitherT (State (BuildsOn z0)) m0) () -> t0
Perhaps you want to add forever to one of these import lists:
Control.Monad.Reader (src/Modes.hs:19:1-58)
Control.Monad.State (src/Modes.hs:20:1-80)
Control.Monad (src/Modes.hs:18:1-27)

/root/editor/src/Modes.hs:160:10: error:
Could not deduce: RootedAt z0 ~ Module SrcSpanInfo
arising from a use of generatePicture
from the context: (MMonad z m, EditorMode z)
bound by the type signature for:
runEditorMode :: (MMonad z m, EditorMode z) =>
State z -> EitherT (State (BuildsOn z)) m Void
at src/Modes.hs:157:1-93
The type variable z0 is ambiguous
In a stmt of a 'do' block: pic <- generatePicture
In the second argument of ($), namely
do { vty <- ask;
pic <- generatePicture;
liftIO $ update vty pic;
handleNextKeyEvent }
In the second argument of ($), namely
forever
$ do { vty <- ask;
pic <- generatePicture;
liftIO $ update vty pic;
handleNextKeyEvent }

--  While building package editor-0.1.0.0 using:

/root/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.24.0.0-ghc-8.0.1
--builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.0.0 build lib:editor
exe:e --ghc-options " -ddump-hi -ddump-to-file"
Process exited with code: ExitFailure 1