import Data.Void
root@c7d36ed66969:~/editor# stack build
Warning (added by new or init): Specified resolver could not satisfy all
dependencies. Some external packages have been added as dependencies.
You can suppress this message by removing it from stack.yaml

No packages found in snapshot which provide a "happy" executable, which
is a build-tool dependency of "haskell-src-exts"
Missing build-tools may be caused by dependencies of the build-tool
being overridden by extra-deps.
This should be fixed soon - see this issue
https://github.com/commercialhaskell/stack/issues/595

editor-0.1.0.0: unregistering (missing dependencies: either)
mmorph-1.0.6: download
mmorph-1.0.6: configure
mmorph-1.0.6: build
mmorph-1.0.6: copy/register
random-1.1: download
random-1.1: configure
random-1.1: build
random-1.1: copy/register
MonadRandom-0.4.2.3: download
MonadRandom-0.4.2.3: configure
MonadRandom-0.4.2.3: build
MonadRandom-0.4.2.3: copy/register
transformers-base-0.4.4: download
transformers-base-0.4.4: configure
transformers-base-0.4.4: build
transformers-base-0.4.4: copy/register
monad-control-1.0.1.0: download
monad-control-1.0.1.0: configure
monad-control-1.0.1.0: build
monad-control-1.0.1.0: copy/register
either-4.4.1.1: download
either-4.4.1.1: configure
either-4.4.1.1: build
either-4.4.1.1: copy/register
editor-0.1.0.0: configure
Configuring editor-0.1.0.0...
editor-0.1.0.0: build
Preprocessing library editor-0.1.0.0...
[1 of 5] Compiling View             ( src/View.hs,
.stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/View.o )
[2 of 5] Compiling Prisms           ( src/Prisms.hs,
.stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Prisms.o )
[3 of 5] Compiling Pretty           ( src/Pretty.hs,
.stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Pretty.o )
[4 of 5] Compiling Printer          ( src/Printer.hs,
.stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Printer.o )

[5 of 5] Compiling Modes            ( src/Modes.hs,
.stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Modes.o )
/root/editor/src/Modes.hs:156:90: error:
Not in scope: type constructor or class Void
Completed 7 action(s).

--  While building package editor-0.1.0.0 using:

/root/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.24.0.0-ghc-8.0.1
--builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.0.0 build lib:editor
exe:e --ghc-options " -ddump-hi -ddump-to-file"
Process exited with code: ExitFailure 1