Fix types again
root@c7d36ed66969:~/editor# stack build
Warning (added by new or init): Specified resolver could not satisfy all
dependencies. Some external packages have been added as dependencies.
You can suppress this message by removing it from stack.yaml

No packages found in snapshot which provide a "happy" executable, which
is a build-tool dependency of "haskell-src-exts"
Missing build-tools may be caused by dependencies of the build-tool
being overridden by extra-deps.
This should be fixed soon - see this issue
https://github.com/commercialhaskell/stack/issues/595

editor-0.1.0.0: build
Preprocessing library editor-0.1.0.0...
[5 of 5] Compiling Modes            ( src/Modes.hs,
.stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Modes.o )

/root/editor/src/Modes.hs:147:53: error:
Expecting one more argument to StateT
(EitherT (State (BuildsOn z)) m) ()
Expected a type, but
StateT (EitherT (State (BuildsOn z)) m) () has kind
* -> *
In the type signature:
handleNextKeyEvent :: (MMonad z m, EditorMode z) =>
StateT (EitherT (State (BuildsOn z)) m) ()

/root/editor/src/Modes.hs:147:61: error:
Expecting one more argument to EitherT (State (BuildsOn z)) m
Expected a type, but
EitherT (State (BuildsOn z)) m has kind
* -> *
In the first argument of StateT, namely
EitherT (State (BuildsOn z)) m
In the type signature:
handleNextKeyEvent :: (MMonad z m, EditorMode z) =>
StateT (EitherT (State (BuildsOn z)) m) ()

/root/editor/src/Modes.hs:147:93: error:
Expected kind * -> *, but () has kind *
In the second argument of StateT, namely ()
In the type signature:
handleNextKeyEvent :: (MMonad z m, EditorMode z) =>
StateT (EitherT (State (BuildsOn z)) m) ()

/root/editor/src/Modes.hs:151:65: error:
Expecting two more arguments to EitherT e
Expected a type, but EitherT e has kind (* -> *) -> * -> *
In the first argument of StateT, namely EitherT e
In the type signature:
juggle :: Monad m =>
(a -> s -> m (Either e s)) -> a -> StateT (EitherT e) m s

--  While building package editor-0.1.0.0 using:

/root/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.24.0.0-ghc-8.0.1
--builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.0.0 build lib:editor
exe:e --ghc-options " -ddump-hi -ddump-to-file"
Process exited with code: ExitFailure 1